[template]
prefix = "/service/pgcluster-tst"
src = "haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
 
check_cmd = "/usr/sbin/haproxy -c -f {{ .src }}"
reload_cmd = "echo reload haproxy && /bin/systemctl reload haproxy"
 
keys = [
    "/members/",
]