---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: install packages
      become: yes
      apt:
        name:
          - ntp
          - ntpdate
          - curl
          - jq
          - python
          - python-dev
          - libpq-dev
        state: present